name: darkpool
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - gradio==6.1.0
    - pandas==1.3.3
    - plotly==5.3.1
    - python-dotenv==0.19.2
    - requests==2.26.0
    - streamlit==1.40.1
prefix: /home/guozehua/miniconda3/envs/darkpool